site_name: My Docs

nav:
  - Home: index.md
  - Lenguajes: 
    -Python: lenguajes/python.md
  - Ceritificaciones:
    - Aws: certificaciones/aws.md
  - Diseño: design/design.md  # Agrega esta línea
  - DevOps:
    - Git: devops/git.md
  - So: so/programas.md
  - Idiomas:
    - Español: idiomas/español.md
  - Tools: 
    - Paginas: tools/tools.md

extra_css:
  - stylesheet/extra.css

plugins:
  - search
  - mermaid2