site_name: My Docs

nav:
  - Home: index.md
  - Lenguajes: lenguajes/python.md
  - Diseño: design/design.md  # Agrega esta línea
  - So: so/programas.md
  - Tools: paginas/tools.md

extra_css:
  - stylesheet/extra.css