site_name: My Docs

nav:
  - Home: index.md
  - ceritificaciones :
    - general : certificaciones/certificaciones.md
    - aws : certificaciones/aws.md
  - lenguajes : 
    - android : lenguajes/android.md
    - python : lenguajes/python.md
    - powershell : lenguajes/powershell.md
    - django : lenguajes/django.md
  - devops :
    - git : devops/git.md
  - so : 
    - so : so/programas.md
    - cables  : so/cables.md
  - ides :
    - vscode : ides/vscode.md
    - vi  : ides/vi.md
  - idiomas :
    - español : idiomas/español.md
  - tools : 
    - paginas : tools/tools.md
    - colabs : tools/colabs.md
  - design :
    - design : design/design.md
    - spinePro : design/spine_pro.md
  - ides :
    - vi : ides/vi.md
  - editores :
    - linux : editores/linux.md
  - seguridad :
    - monitoreo : seguridad/monitoreo.md
    - seguridad : seguridad/seguridad.md
  - hardware :
    - asus-desktop : hardware/asus-desktop.md
    - amd-raizen-9-7900 : hardware/amd-raizen-9-7900.md
    - particiones : hardware/particiones.md
  - certificaciones :
    - aws : certificaciones/aws.md
# hola

extra_css:
  - stylesheet/extra.css

plugins:
  - search
  - mermaid2
