site_name: My Docs

nav:
  - Home: index.md
  - 'Ceritificaciones':
    - 'General': 'certificaciones/certificaciones.md'
    - 'Aws': 'certificaciones/aws.md'
  - Lenguajes: 
    - Python: lenguajes/python.md
    - Powershell: lenguajes/powershell.md
  - DevOps:
    - Git: devops/git.md
  - So: so/programas.md
  - IDES:
    - Vscode: ides/vscode.md
  - Idiomas:
    - Español: idiomas/español.md
  - Tools: 
    - Paginas: tools/tools.md
  - Diseño: design/design.md  # Agrega esta línea
    - SpinePro: design/spine_pro.md

extra_css:
  - stylesheet/extra.css

plugins:
  - search
  - mermaid2